### PR TITLE
Ensure that generated onion packets have correct length

### PR DESCRIPTION
**Pull request by kurnevsky**

### CODE REVIEW

**Comment by kpp** [comment]
`pub const MAX_DHT_PACKET_SIZE: usize = 512;`.

**Comment by kurnevsky** [comment]
And it's not correct, we will have to increase this limit.
Anyway all onion packets have separate limit of 1400 bytes so this pr makes sence.

**Comment by kpp** [comment]
This PR does make little sense since DhtCodec uses buffer with 512 bytes. So there no way to pass even 1399 bytes with onion packet

**Comment by kurnevsky** [comment]
And as I already said it's not correct. We will have to increase this limit. And I believe it must be much more than 1400 bytes.

**Comment by kpp** [comment]
Then increase it in the current PR.

**Comment by kurnevsky** [comment]
Increased to 2048, c-toxcore has the same limit:
```c
#define MAX_UDP_PACKET_SIZE 2048
```

**Pull request merged**
