### PR TITLE
Move to `rust_sodium 0.10.1`

### PR DESCRIPTION
**Pull request by suhr**
Let's do it.

### CODE REVIEW

**Comment by suhr** [comment]
```
running: "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "bzip2-1.0.6" "-D_WIN32" "-DBZ_EXPORT" "-DBZ_NO_STDIO" "-o" "C:\\projects\\tox\\target\\debug\\build\\bzip2-sys-d0f67c7c306aa840\\out\\bzip2-1.0.6\\blocksort.o" "-c" "bzip2-1.0.6/blocksort.c"
--- stderr
thread 'main' panicked at '
Internal error occurred: Failed to find tool. Is `gcc.exe` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)
```

That's interesting. `bzip2` seems to need a whole gcc to compile.

**Comment by suhr** [comment]
I'll try to switch it to `stable-msvc`, hopefully it will help.

**Comment by suhr** [comment]
And it indeed helps. :shipit:

**Comment by kurnevsky** [comment]
What's the reason for this change?

**Comment by kpp** [comment]
We are stuck to sodiumoxide 0.0.16 so we will not get updates. They are fixing the bug https://github.com/tox-rs/tox/pull/160 for months

**Comment by kurnevsky** [comment]
Isn't it fixed with this PR: https://github.com/sodiumoxide/sodiumoxide/pull/265
It seems we just need to wait for a new version.

**Comment by suhr** [comment]
It is trivial to switch back if required. So there's no need to wait.

**Comment by kpp** [comment]
> By the way, should I rebase this as chore(deps): move to rust_sodium v0.10.1?

Yes

> It seems we just need to wait for a new version.

Let's wait for a few days, specially for that: https://github.com/sodiumoxide/sodiumoxide/pull/258

**Comment by suhr** [comment]
Seems like we've got the [Unexpected PDB error](https://stackoverflow.com/questions/4256524/lnk1318-unexpected-pdb-error-ok-0).

**Comment by Dylan-DPC** [comment]
Sodiumoxide co-maintainer here. Sorry about this. None of us work on windows systems and got busy with other stuff so fixing it took time. That said if anyone wants to fix it for us by pushing the required changes to sodiumoxide/sodiumoxide#258 and will issue a new release soon after so that this change isn't needed. Thanks

**Comment by kpp** [comment]
Closed in favor of https://github.com/sodiumoxide/sodiumoxide/issues/293

**Pull request closed without merging**
