### PR TITLE
WIP: Rustfmt

### PR DESCRIPTION
**Pull request by suhr**
Rustfmt is not ready for production. `overflow_delimited_expr` is not available in nightly yet, and some required options do not even exist.

Related rustfmt issues:

- ~~https://github.com/rust-lang-nursery/rustfmt/issues/3207~~
- https://github.com/rust-lang-nursery/rustfmt/issues/3208

### CODE REVIEW

**Comment by kpp** [comment]
Integrate rustfmt check into TravisCI and GitlabCI configs

**Comment by suhr** [comment]
Will do, later (note that rustfmt is usable only on nightly).

**Comment by kpp** [comment]
https://github.com/rust-lang/rustfmt/issues/2570

**Comment by kpp** [comment]
https://www.reddit.com/r/rust/comments/9jl6a9/pro_tip_if_you_use_cargo_fmtrustfmt_use_a/e6snrkj/

**Pull request closed without merging**
