### PR TITLE
Add crypto_init() to all tests which use sodium

### LINKED ISSUE #279: Sometimes, cargo test fails on Mac OSX
```rust
failures:

---- toxcore::crypto_core::tests::encrypt_data_symmetric_test stdout ----
thread 'toxcore::crypto_core::tests::encrypt_data_symmetric_test' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    toxcore::crypto_core::tests::encrypt_data_symmetric_test

test result: FAILED. 527 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

### PR DESCRIPTION
**Pull request by NamsooCho**
Close #279

### CODE REVIEW

**Comment by kpp** [comment]
Does it help to `cargo test -- --test-threads=4`?

**Comment by NamsooCho** [comment]
Yes. I am using 4 core, 8 threads CPU.

**Comment by kpp** [comment]
How many times did you run `cargo test`?

**Comment by kpp** [comment]
diff stat: `+231 -0`. How is it possible? We got ~580` tests and you changed only 231?

**Comment by NamsooCho** [comment]
I didn't add `crypt_init()` to test function which is not using sodium.
And I run it 40 times with 8 threads.

**Comment by NamsooCho** [comment]
For example,
https://github.com/tox-rs/tox/blob/738c9598f63ea51ac8ca19de00d8778d2a0ed15f/src/toxcore/dht/server/mod.rs#L1427

this fn is called by almost every test fn.

**Comment by kurnevsky** [comment]
What about toxencryptsave tests?

**Comment by kpp** [comment]
From sodiumoxide: `pub fn init() -> Result<(), ()>`, maybe we should change the API to return Result and to be warned about unused result? Then we can use `crypto_init().unwrap()`

**Comment by kurnevsky** [comment]
@kpp do we need to wrap `sodiumoxide::init()` in this case?

**Comment by kpp** [comment]
Why not?

**Comment by kurnevsky** [comment]
What purpose does it serve?

**Comment by kpp** [comment]
You don’t call a function from external crate to make it work

**Comment by kurnevsky** [comment]
> You don’t call a function from external crate to make it work

It would make sense if we had wrappers for all sodiumoxide functions and types. But we call sodiumoxide directly from a lot of places (`gen_key()`, `gen_nonce()`, etc) and use its types (PublicKey, Nonce, etc). So wrapping only `init()` seems useless to me - it can't simplify anything, but we have to remember about this custom wrapper and what it does.

**Comment by kpp** [comment]
> But we call sodiumoxide directly from a lot of places

Yes but we don't call it from tox-node, which is a final product.

**Comment by kurnevsky** [comment]
> Yes but we don't call it from tox-node, which is a final product.

ok then, let it be wrapped.

**Pull request merged**
