### PR TITLE
Add macros for errors

### PR DESCRIPTION
**Pull request by kurnevsky**

### CODE REVIEW

**Comment by kpp** [comment]
Nice. Are these all errors implemented?

**Comment by kurnevsky** [comment]
Yes. There are other improvements can be made but I'd left them for another PR.

**Comment by kpp** [comment]
Rebase on master

**Comment by kurnevsky** [comment]
It was already rebased to the latest master. Though appvayor failed to build it. So I repushed the last commit, let's see...

**Pull request merged**
