### PR TITLE
Drop MIT license

### PR DESCRIPTION
**Pull request by kurnevsky**
Making PR to start discussion on the license we use.

One of the reasons why we need to do it is that `tox-rs` is a derived work of `c-toxcore` as it borrows many algorighms/approaches from `c-toxcore` and therefore has to inherit its license.

### CODE REVIEW

**Comment by kpp** [comment]
How about GPL with permissions to post the code onto App Store?

**Comment by kurnevsky** [comment]
Should we get an approval from toktok team for that? Ping @zugz

**Comment by iphydf** [comment]
No need for approval. This action is legal.

**Comment by kurnevsky** [comment]
Pushed a note about Apple App Store. The text is taken from https://github.com/nextcloud/ios/blob/master/COPYING.iOS

**Comment by kpp** [comment]
Thanks. We need to fix clippy warnings (in another PR probably).

**Pull request merged**
