### PR TITLE
Add function for unbiased random numbers

### PR DESCRIPTION
**Pull request by kurnevsky**
Later it will be used to choose random nodes for onion paths

### CODE REVIEW

**Comment by kpp** [comment]
https://rust-random.github.io/rand/src/rand/distributions/uniform.rs.html#403

Would you please check it?

**Comment by kurnevsky** [comment]
@kpp they do the same but with multiplication instead of modulo. Honestly, I don't know why. Perhaps it's more performant even though much more complex. In terms of correctness my version should be fine. Alternatively we can use `rand` crate instead of libsodium but I'd left it for the future.

**Comment by kurnevsky** [comment]
@kpp right, it's because of performance: https://github.com/rust-random/rand/issues/570#issuecomment-408523182

**Comment by kpp** [comment]
rebase

**Pull request merged**
