### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by kurnevsky**

### CODE REVIEW

**Comment by kpp** [comment]
```
warning: lint name `new_without_default` is deprecated and may not have an effect in the future. Also `cfg_attr(cargo-clippy)` won't be necessary anymore
-->src/lib.rs:9:45
|
9|#![cfg_attr(feature = "cargo-clippy", allow(new_without_default, new_without_default_derive))]
|^^^^^^^^^^^^^^^^^^^help: change it to: `clippy::new_without_default`
|
=note: #[warn(renamed_and_removed_lints)] on by default
```

And so on. See https://travis-ci.org/tox-rs/tox/jobs/428553447#L1591

**Comment by kpp** [comment]
There is no clippy-preview on `nightly`, but on beta and stable we get:

```
error[E0554]: #![feature] may not be used on the stable release channel
 --> src/lib.rs:8:39
  |
8 | #![cfg_attr(feature = "cargo-clippy", feature(tool_lints))]
  |                                       ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

```
error[E0554]: #![feature] may not be used on the beta release channel
 --> src/lib.rs:8:39
  |
8 | #![cfg_attr(feature = "cargo-clippy", feature(tool_lints))]
  |                                       ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by kurnevsky** [comment]
@kpp what do you mean no `clippy-preview` on `nightly`? I used nightly to check these warnings.
The thing is that we either use unstable feature `feature(tool_lints)` or have warnings you noted in the previous message (those prefixes are unstable).

**Comment by kpp** [comment]
https://travis-ci.org/tox-rs/tox/jobs/429033754

**Comment by kpp** [comment]
They fixed it in `rustc 1.30.0-nightly (e4ba1d41e 2018-09-15)`.

How about

```
warning: redundant field names in struct initialization                                                                            
    --> src/toxcore/net_crypto/mod.rs:2522:13                                                                                      
     |                                                                                                                             
2522 |             session_precomputed_key: session_precomputed_key,                                                               
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `session_precomputed_key`      
```

**Pull request merged**
