### PR TITLE
WIP: Replace Mutex<u64> with AtomicU64

### PR DESCRIPTION
**Pull request by NamsooCho**

### CODE REVIEW

**Comment by kurnevsky** [comment]
AtomicUsize should be replaced with AtomicU64, but not the Mutex. We should check with attr `target_has_atomic` if the target has this atomic and if not - fallback to the mutex.

**Comment by kpp** [comment]
I thought since it is in stable we should not care

**Comment by kurnevsky** [comment]
There might be platforms with no AtomicU64 support. That's why they are behind target_has_atomic flag. I'm not sure what exact platforms have no AtomicU64 (it seems x86 has it?) but either way we should not have both AtomicU64 and AtomicUsize at the same time.

**Comment by kpp** [comment]
Are you sure about that? There is no info about it in the module documentation

**Comment by kurnevsky** [comment]
Check https://github.com/rust-lang/rfcs/blob/master/text/1543-integer_atomics.md#target-support

**Comment by kpp** [comment]
This is a 2016 RFC. I want a little bit fresher info

**Comment by kurnevsky** [comment]
@kpp see module documentation https://doc.rust-lang.org/std/sync/atomic/index.html

> PowerPC and MIPS platforms with 32-bit pointers do not have AtomicU64 or AtomicI64 types.
> ARM platforms like armv5te that aren't for Linux do not have any atomics at all.
> ARM targets with thumbv6m do not have atomic operations at all.

**Comment by kpp** [comment]
Thanks. Then we should fallback to mutexes instead

**Comment by NamsooCho** [comment]
https://github.com/rust-lang/rust/issues/32976#issuecomment-476049327
Issue re-opened.

**Comment by kurnevsky** [comment]
It's fine now but doesn't compile on stable rust. We can either wait when `target_has_atomic` attribute is stabilized or use `target_pointer_width` as before.

**Comment by kpp** [comment]
wait when target_has_atomic attribute is stabilized

**Comment by kpp** [comment]
https://github.com/tox-rs/tox/pull/406

**Pull request closed without merging**
